// Autogenerated with StateSmith 0.9.10-alpha+1f83cb59adcabe0a5a4c8d3e0421027761c28974.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once
#include <stdint.h>

typedef enum __attribute__((packed)) TvRemoteSm_EventId
{
    TvRemoteSm_EventId_B1_LONG_PRESS = 0,
    TvRemoteSm_EventId_B1_PRESS = 1,
    TvRemoteSm_EventId_B2_LONG_PRESS = 2,
    TvRemoteSm_EventId_B2_PRESS = 3,
} TvRemoteSm_EventId;

enum
{
    TvRemoteSm_EventIdCount = 4
};

typedef enum __attribute__((packed)) TvRemoteSm_StateId
{
    TvRemoteSm_StateId_ROOT = 0,
    TvRemoteSm_StateId_TV_OFF = 1,
    TvRemoteSm_StateId_TV_ON = 2,
    TvRemoteSm_StateId_BRIGHTNESS_CHANGE = 3,
    TvRemoteSm_StateId_BRIGHTNESS_CHANGE__INITIAL = 4,
    TvRemoteSm_StateId_BRIGHTNESS_DOWN = 5,
    TvRemoteSm_StateId_BRIGHTNESS_UP = 6,
    TvRemoteSm_StateId_CHANNEL_SELECT = 7,
    TvRemoteSm_StateId_CHANNEL_DOWN = 8,
    TvRemoteSm_StateId_CHANNEL_SELECT__INITIAL = 9,
    TvRemoteSm_StateId_CHANNEL_UP = 10,
    TvRemoteSm_StateId_VOLUME_CHANGE = 11,
    TvRemoteSm_StateId_VOLUME_CHANGE__INITIAL = 12,
    TvRemoteSm_StateId_VOLUME_DOWN = 13,
    TvRemoteSm_StateId_VOLUME_UP = 14,
} TvRemoteSm_StateId;

enum
{
    TvRemoteSm_StateIdCount = 15
};


// Generated state machine
// forward declaration
typedef struct TvRemoteSm TvRemoteSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct TvRemoteSm_Vars
{
    unsigned short volume = 50;     
    unsigned short brightness = 50;   
    unsigned short channel = 1;
} TvRemoteSm_Vars;


// event handler type
typedef void (*TvRemoteSm_Func)(TvRemoteSm* sm);

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TvRemoteSm_ctor(TvRemoteSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TvRemoteSm_start(TvRemoteSm* sm);

// Dispatches an event to the state machine. Not thread safe.
void TvRemoteSm_dispatch_event(TvRemoteSm* sm, TvRemoteSm_EventId event_id);

// Thread safe.
char const * TvRemoteSm_state_id_to_string(TvRemoteSm_StateId id);

// Thread safe.
char const * TvRemoteSm_event_id_to_string(TvRemoteSm_EventId id);

// Generated state machine
struct TvRemoteSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TvRemoteSm_StateId state_id;
    
    // Used internally by state machine. Don't modify.
    TvRemoteSm_Func ancestor_event_handler;
    
    // Used internally by state machine. Don't modify.
    TvRemoteSm_Func current_event_handlers[TvRemoteSm_EventIdCount];
    
    // Used internally by state machine. Don't modify.
    TvRemoteSm_Func current_state_exit_handler;
    
    // Variables. Can be used for inputs, outputs, user variables...
    TvRemoteSm_Vars vars;
};

